[libraries]
spoon = "fr.inria.gforge.spoon:spoon-core:10.4.2"
jagr = "org.sourcegrade:jagr-launcher:0.10.3"
mockito = "org.mockito:mockito-core:5.12.0"
junit = "org.junit.jupiter:junit-jupiter:5.10.0"
asm = "org.ow2.asm:asm:9.7"
dokkaKotlinAsJavaPlugin = "org.jetbrains.dokka:kotlin-as-java-plugin:1.9.0"
dokkaBase = "org.jetbrains.dokka:dokka-base:1.9.0"
[plugins]
dokka = "org.jetbrains.dokka:1.9.20"
